default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'aleks' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'aleksrocks' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>

development:
  <<: *default
  database: blackseawebsite_development

test:
  <<: *default
  database: blackseawebsite_test

production:
  <<: *default
  database: blackseawebsite_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>