default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'aleks' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'aleksrocks' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>

development:
  <<: *default
  database: blackseawebsite_development

test:
  <<: *default
  database: blackseawebsite_test

production:
  adapter: postgresql
  encoding: unicode
  database: blacksea_db
  pool: 5
  username: blacksea_user
  password: blacksea_password
  host: 127.0.0.1
  port: 5432
